### ISSUE TITLE
Module name change

### ISSUE THREAD

**Issue by sbgraphicdesign** [backdrop-contrib/blizz_vanisher#3]
I'd like to suggest a name change for the module. It's pretty meaningless and I think it should at least have the word 'cookie' in the name so it gets picked up on a module search.

To that end, here are my suggestions:

- Cookie Vanisher
- GDPR Cookies

**Comment by Graham-72** [comment]
I have converted and re-published this module as GDPR Cookies (gdpr_cookies) which has been released.

I propose not to release this version but to keep it here in backdrop-contrib in order to preserve its history.

I do not propose to release or make further changes to this module.
